name: waven
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  json_annotation: ^4.9.0
  get_it: ^9.1.1
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.2
  http: ^1.6.0
  go_router: ^17.0.0
  logger: ^2.6.2
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  meta: ^1.17.0
  equatable: ^2.0.7
  dio: ^5.9.0
  lottie: ^3.3.2
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  
flutter:
  uses-material-design: true
  assets:
    -  assets/logo/
    -  assets/lottie/

